### ISSUE TITLE
Trouble with configuration.yaml

### ISSUE THREAD

**Issue by bluntiless** [ColinRobbins/Homeassistant-Lightwave-TRV#1]
Hi @ColinRobbins 

I am having trouble with adding this to my configuration.yaml as it keeps throwing this error:

Invalid config for [lightwave]: expected a dictionary for dictionary value @ data['lightwave']['trv']. Got None

I have copied the exact config example that you provided but still throwing the errors. Any advice you can offer would be appreciated. I had this up and running using your previous HAP-NodeJS version for quite a few years but like you, I have changed over to the Homeassistant family.

**Comment by ColinRobbins** [comment]
Hello, can you please provide your exact configuration?
Have you compared it to the configuration described in: https://www.home-assistant.io/integrations/lightwave/

**Comment by bluntiless** [comment]
Hi, here it is:

lightwave:
  host: '192.168.0.xx'
  lights:
    R1D1:
      name: Bedroom lights
    R6D1:
      name: Landing lights
    R4D2:
      name: Front lights
    R4D1:
      name: Back lights
    R7D1:
      name: Hallway lights
    R9D2:
      name: Dining lights
    R8D1:
      name: Baby Room lights
    R3D1:
      name: Garden lights 
    R4D4:
      name: Standlight lights
      
    trv:
      trv_proxy_ip: 127.0.0.1
      
      trv_proxy_port: 7878
      trvs:
      R1Dh:
      name: Bedroom TRV
      serial: 0B2902

**Comment by ColinRobbins** [comment]
I think you have some formatting issues there, getting the indentation correct is crucial, without the blank line too.
Looks like you need:
```
lightwave:
  host: '192.168.0.xx' 
  lights:
    R1D1:
      name: Bedroom lights
  trv:
    trv_proxy_ip: 127.0.0.1
    trv_proxy_port: 7878
    trvs:
      R1Dh:
        name: Bedroom TRV
        serial: 0B2902
```

**Comment by bluntiless** [comment]
Hi again Colin,

I copied the above and commented out everything else and I am getting this error:
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:383 
Integration: Hass.io (documentation, issues) 
First occurred: 20:47:10 (3 occurrences) 
Last logged: 21:08:07

Invalid config for [lightwave]: [trv] is an invalid option for [lightwave]. Check: lightwave->lightwave->lights->R4D4->trv. (See /config/configuration.yaml, line 129).
Component error: trv - Integration 'trv' not found.
Invalid config for [lightwave]: [trv_proxy_ip] is an invalid option for [lightwave]. Check: lightwave->lightwave->trv->trv_proxy_ip. (See /config/configuration.yaml, line 157).
What am I doing wrong? I have been scratching my head over this issue for 2 days now.

**Comment by ColinRobbins** [comment]
The line:
```
Invalid config for [lightwave]: [trv] is an invalid option for [lightwave]. Check: lightwave->lightwave->lights->R4D4->trv. (See /config/configuration.yaml, line 129).
```
suggests you have something like:
```
lightwave:
  host: '192.168.0.xx' 
  lights:
    R1D1:
      name: Bedroom lights
      trv:
```
i.e., the `trv` line is indented to much.   It should be indented to the same level as the `lights`.
Also, just to check, you are using the latest homeassistant, which has the the `lightwave` TRV element build in.
(Older versions required a `custom_component/lightwave` directory in home assistant, where the configuration was different - if you have a `custom_component/lightwave` in your homeassistant config, remove it as it been replaced by code builtin to home assistant).
If this does not help, please paste your exact configuration, correctly formatted as code using the "insert code" option, so I can see the exact formatting.

**Comment by ColinRobbins** [comment]
Also, make sure the `configuration.yaml` is using spaces only, and no tab characters.

**Comment by bluntiless** [comment]
Still can't get this sorted.  What am I doing incorrectly? Here is my configuration.yaml:

--- 
alarm_control_panel: 
  - platform: manual
    armed_home: 
      delay_time: 0
    code: 1321
    delay_time: 0
    disarmed: 
      trigger_time: 300
    name: "Home Alarm"
    trigger_time: 10
#apple_tv_mrp:
  #- #name: Living Room Apple TV
    #host: 192.168.4.24
    #port: 49152
    #credentials: 3d594d252e442a544af60223caa23d72bf0e8234253c4a97e8f49778efc0ece8:26b01a3ea34141e2529601e0cb2326baa49b2eb055bb2e637c69753059bb073f:33653566376462642d653538642d343735612d613766642d613932363332646365383433:34373664643938312d376633322d343962632d623531312d613266663161623866616366

automation: 
  - 
    action: 
      entity_id: alarm_control_panel.home_alarm
      service: alarm_control_panel.alarm_trigger
    alias: "Trigger alarm while armed away"
    condition: 
      - 
        condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_away
    trigger: 
      - 
        entity_id: binary_sensor.front_door
        platform: state
        to: active
      - 
        entity_id: binary_sensor.kitchen_pir
        platform: state
        to: "on"
      - 
        entity_id: binary_sensor.landing_pir
        platform: state
        to: "on"
      - 
        entity_id: binary_sensor.hallway_pir
        platform: state
        to: "on"
      - 
        entity_id: binary_sensor.lounge_pir
        platform: state
        to: "on"
      - 
        entity_id: switch.siren
        platform: state
        to: active
tuya:
  platform: smart_life
  username: 'waynezillas@hotmail.co.uk'
  password: thgirw47
  country_code: '61'
config: ~
logger:
  default: warning
  logs:
    homeassistant.components.homekit: debug
    pyhap: debug
mobile_app:
cloud:
discovery: ~
frontend:
 themes: !include_dir_merge_named themes
# hacs:
  #token: 93fdc48d7188e5fb50bd77eadc8feb12afae28f9
homekit:
  media_player.media_player.ue55c7000_samsung_dtv_rcr:
    name: "TV"
    feature_list:
      - feature: on_off
      - feature: play_pause
      - feature: play_stop
      - feature: toggle_mute
      - feature: volume_up
      - feature: volume_down
    alarm_control_panel.home_alarm: 
      code: '1321'  
  #   - feature: on_off
   #    - feature: toggle_mute
      #- alarm_control_panel
      #- light
     # - media_player
     # - switch
    #include_entities: 
    #  - binary_sensor.front_door
     # - binary_sensor.hallway_pir
     # - binary_sensor.kitchen_pir
      #- binary_sensor.landing_pir
      #- binary_sensor.lounge_pir
     # - binary_sensor.smoke_alarm
     # - switch.siren
     # - sensor.blink_bedroom_temperature
      #- sensor.blink_changing_room_temperature
      #- binary_sensor.blink_back_garden_motion_detected
      #- binary_sensor.blink_bedroom_motion_detected
konnected: 
  access_token: thgirw49
  api_host: "http://192.168.0.87:8123"
  devices: 
    - 
      binary_sensors: 
        - 
          name: "Front Door"
          type: door
          zone: 1
        - 
          name: "Hallway Pir"
          type: motion
          zone: 2
        - 
          name: "Lounge Pir"
          type: motion
          zone: 3
        - 
          name: "Kitchen Pir"
          type: motion
          zone: 4
        - 
          name: "Smoke Alarm"
          type: smoke
          zone: 5
        - 
          name: "Landing Pir"
          type: motion
          zone: 6
      host: "192.168.4.30"
      id: 84f3ebfc96f1
      port: "24553"
      switches: 
        - 
          name: siren
          zone: out
#simpleicons:
logbook:
history:
stream:
system_health: ~
#camera:
 # - platform: ffmpeg
  #  name: Motorola Mia's Bedroom
    #platform: ffmpeg
    # name: Driveway
    #input: -rtsp_transport tcp -i rtsp://192.168.0.83:554/user=admin&password=&channel=1&stream=0.sdp?/
    # name: Hallway
   # input: -rtsp_transport tcp -i rtsp://192.168.0.83:554/user=admin&password=&channel=3&stream=0.sdp?/
  #- platform: ffmpeg
   #  input: -rtsp_transport tcp -i rtsp://192.168.0.83:554/user=admin&password=&channel=4&stream=0.sdp?/
#ffmpeg:
#ffmpeg_bin: /home/homeassistant/lib/python3.7/site-packages/homeassistant/components/ffmpeg
#blink:
  #username: 'waynezillas@hotmail.co.uk'
  #password: 'thgirw48'
  #scan_interval: 300

#lightwave:
  #host: '192.168.0.18'
  #trv_proxy_ip: 127.0.0.1
  #trv_proxy_port: 7878
  #lights:
    #R1D1:
      #name: Bedroom lights
    #R6D1:
      #name: Landing lights
    #R4D2:
      #name: Front lights
    #R4D1:
      #name: Back lights
    #R7D1:
      #name: Hallway lights
    #R9D2:
      #name: Dining lights
    #R8D1:
      #name: Baby Room lights
    #R3D1:
      #name: Garden lights 
    #R4D4:
      #name: Standlight lights
  #trv:
    #R1Dh:
      #name: Bedroom TRV
      #serial: 0B2902
lightwave:
  host: 192.168.0.18
  lights:
    R1D1:
      name: Master bedroom lights
    R1D4:
      name: Landing lights
    R7D1: 
      name: Hallway lights
    R9D4:
      name: Dining lights
    R8D1:
      name: Mia's bedroom lights
    R3D1:
      name: Garden wall lights
    R4D3:
      name: Living room lights 
    R4D4:
      name: Standlight lights
  trv:
      trv_proxy_ip: 127.0.0.1
      trv_proxy_port: 7878
      trvs:
        R1Dh:
          name: Bedroom TRV
          serial: 0B2902

**Comment by bluntiless** [comment]
Hi Colin, still can't figure this out so here is my configuration.yaml. Thanks for the advice by the way. 


--- 
alarm_control_panel: 
  - platform: manual
    armed_home: 
      delay_time: 0
    code:'xxxx'
    delay_time: 0
    disarmed: 
      trigger_time: 300
    name: "Home Alarm"
    trigger_time: 10
automation: 
  - 
    action: 
      entity_id: alarm_control_panel.home_alarm
      service: alarm_control_panel.alarm_trigger
    alias: "Trigger alarm while armed away"
    condition: 
      - 
        condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_away
    trigger: 
      - 
        entity_id: binary_sensor.front_door
        platform: state
        to: active
      - 
        entity_id: binary_sensor.kitchen_pir
        platform: state
        to: "on"
      - 
        entity_id: binary_sensor.landing_pir
        platform: state
        to: "on"
      - 
        entity_id: binary_sensor.hallway_pir
        platform: state
        to: "on"
      - 
        entity_id: binary_sensor.lounge_pir
        platform: state
        to: "on"
      - 
        entity_id: switch.siren
        platform: state
        to: active
tuya:
  platform: smart_life
  username: 'xxxxxxxxxxx@hotmail.co.uk'
  password: xxxxxxxx
  country_code: '61'
config: ~
logger:
  default: warning
  logs:
    homeassistant.components.homekit: debug
    pyhap: debug
mobile_app:
cloud:
discovery: ~
frontend:
 themes: !include_dir_merge_named themes
# hacs:
  #token: 93fdc48d7188e5fb50bd77eadc8feb12afae28f9
homekit:
  media_player.media_player.ue55c7000_samsung_dtv_rcr:
    name: "TV"
    feature_list:
      - feature: on_off
      - feature: play_pause
      - feature: play_stop
      - feature: toggle_mute
      - feature: volume_up
      - feature: volume_down
    alarm_control_panel.home_alarm: 
      code: '1321'  
konnected: 
  access_token: xxxxxxx
  api_host: "http://192.168.0.xx:8123"
  devices: 
    - 
      binary_sensors: 
        - 
          name: "Front Door"
          type: door
          zone: 1
        - 
          name: "Hallway Pir"
          type: motion
          zone: 2
        - 
          name: "Lounge Pir"
          type: motion
          zone: 3
        - 
          name: "Kitchen Pir"
          type: motion
          zone: 4
        - 
          name: "Smoke Alarm"
          type: smoke
          zone: 5
        - 
          name: "Landing Pir"
          type: motion
          zone: 6
      host: "192.168.4.xx"
      id: 84f3ebfc96f1
      port: "24553"
      switches: 
        - 
          name: siren
          zone: out
#simpleicons:
logbook:
history:
stream:
system_health: ~
lightwave:
  host: 192.168.0.xx
  lights:
    R1D1:
      name: Master bedroom lights
    R1D4:
      name: Landing lights
    R7D1: 
      name: Hallway lights
    R9D4:
      name: Dining lights
    R8D1:
      name: Mia's bedroom lights
    R3D1:
      name: Garden wall lights
    R4D3:
      name: Living room lights 
    R4D4:
      name: Standlight lights
  trv:
      trv_proxy_ip: 127.0.0.1
      trv_proxy_port: 7878
      trvs:
        R1Dh:
          name: Bedroom TRV
          serial: 0B2902

**Comment by ColinRobbins** [comment]
Sorry, I can't tell with this config file as shown as I can't see the indentation - which is crucial.
If you use the "insert code" `<>` in the formatting bar, then place the config there, it will preserve the indentations.

Can you also please check that you do NOT have a folder in your homeassistant configuration called `custom_components/lightwave`.  It looks a bit like it might be picking up the way this used to work, before integrated into HomeAssistant.

Also, what version of HomeAssistant are you running?

**Comment by bluntiless** [comment]
I did try to use the insert code <> icon. Unfortunately I have never used it before and was unsure. I have now searched how to use it. Also I am on the latest version of Home Assistant 0.117.6 and yes I did have a Custom component folder but have since  deleted it when you mentioned it.
```
--- 
alarm_control_panel: 
  - platform: manual
    armed_home: 
      delay_time: 0
    code:'xxxx'
    delay_time: 0
    disarmed: 
      trigger_time: 300
    name: "Home Alarm"
    trigger_time: 10
automation: 
  - 
    action: 
      entity_id: alarm_control_panel.home_alarm
      service: alarm_control_panel.alarm_trigger
    alias: "Trigger alarm while armed away"
    condition: 
      - 
        condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_away
    trigger: 
      - 
        entity_id: binary_sensor.front_door
        platform: state
        to: active
      - 
        entity_id: binary_sensor.kitchen_pir
        platform: state
        to: "on"
      - 
        entity_id: binary_sensor.landing_pir
        platform: state
        to: "on"
      - 
        entity_id: binary_sensor.hallway_pir
        platform: state
        to: "on"
      - 
        entity_id: binary_sensor.lounge_pir
        platform: state
        to: "on"
      - 
        entity_id: switch.siren
        platform: state
        to: active
tuya:
  platform: smart_life
  username: 'xxxxxxxxxxx@hotmail.co.uk'
  password: xxxxxxxx
  country_code: '61'
config: ~
logger:
  default: warning
  logs:
    homeassistant.components.homekit: debug
    pyhap: debug
mobile_app:
cloud:
discovery: ~
frontend:
 themes: !include_dir_merge_named themes
# hacs:
  #token: 93fdc48d7188e5fb50bd77eadc8feb12afae28f9
homekit:
  media_player.media_player.ue55c7000_samsung_dtv_rcr:
    name: "TV"
    feature_list:
      - feature: on_off
      - feature: play_pause
      - feature: play_stop
      - feature: toggle_mute
      - feature: volume_up
      - feature: volume_down
    alarm_control_panel.home_alarm: 
      code: '1321'  
konnected: 
  access_token: xxxxxxx
  api_host: "http://192.168.0.xx:8123"
  devices: 
    - 
      binary_sensors: 
        - 
          name: "Front Door"
          type: door
          zone: 1
        - 
          name: "Hallway Pir"
          type: motion
          zone: 2
        - 
          name: "Lounge Pir"
          type: motion
          zone: 3
        - 
          name: "Kitchen Pir"
          type: motion
          zone: 4
        - 
          name: "Smoke Alarm"
          type: smoke
          zone: 5
        - 
          name: "Landing Pir"
          type: motion
          zone: 6
      host: "192.168.4.xx"
      id: 84f3ebfc96f1
      port: "24553"
      switches: 
        - 
          name: siren
          zone: out
#simpleicons:
logbook:
history:
stream:
system_health: ~
lightwave:
  host: 192.168.0.xx
  lights:
    R1D1:
      name: Master bedroom lights
    R1D4:
      name: Landing lights
    R7D1: 
      name: Hallway lights
    R9D4:
      name: Dining lights
    R8D1:
      name: Mia's bedroom lights
    R3D1:
      name: Garden wall lights
    R4D3:
      name: Living room lights 
    R4D4:
      name: Standlight lights
  trv:
      trv_proxy_ip: 127.0.0.1
      trv_proxy_port: 7878
      trvs:
        R1Dh:
          name: Bedroom TRV
          serial: 0B2902
```

**Comment by ColinRobbins** [comment]
Ah, there is an extra "trv_"  `trv_proxy_ip` should be `proxy_ip`.   
You've also got a couple of extra spaces in there, not sure if they are signifincant or not.
Anyway, try...
```
lightwave:
  host: 192.168.0.xx
  lights:
    R1D1:
      name: Master bedroom lights
  trv:
    proxy_ip: 127.0.0.1
    proxy_port: 7878
    trvs:
      R1Dh:
        name: Bedroom TRV
        serial: 0B2902
```
The above loads OK on my test system.

**Comment by ColinRobbins** [comment]
I also noticed you reference my old Node_JS code for doing this.   I presume this means you use Apple Homekit too.
If you add:
```
homekit:
  filter:
    include_domains:
      - climate
```
the TRVs will appear in Apple HomeKit!
(You'll need to follow the Setup instructions for homekit in: https://www.home-assistant.io/integrations/homekit/)
